version: '3'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-playground 
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - .:/app

